package Main;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import database_connector.DBKonek;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.draw.LineSeparator;

import java.io.File;
import java.io.FileOutputStream;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.io.File;
import java.io.FileOutputStream;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class Signup extends javax.swing.JFrame {

    /**
     * 
     */
    public Signup() {
        initComponents();
    }
    private void clearField(){
        usernameSignup.setText("");
        emailSignup.setText("");
        passwordSignup.setText("");
        confirmpassword.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createaccbttn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        returnlogin = new javax.swing.JButton();
        emailSignup = new javax.swing.JTextField();
        usernameSignup = new javax.swing.JTextField();
        showPass1 = new javax.swing.JCheckBox();
        showPass2 = new javax.swing.JCheckBox();
        passwordSignup = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 588));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("SIGN UP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel6.setText("Confirm Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        createaccbttn.setBackground(new java.awt.Color(77, 77, 77));
        createaccbttn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        createaccbttn.setForeground(new java.awt.Color(255, 255, 255));
        createaccbttn.setText("Create account");
        createaccbttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createaccbttn.setBorderPainted(false);
        createaccbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccbttnActionPerformed(evt);
            }
        });
        jPanel1.add(createaccbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 130, 30));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel8.setText("I have an account");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, 20));

        returnlogin.setBackground(new java.awt.Color(51, 51, 51));
        returnlogin.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        returnlogin.setForeground(new java.awt.Color(255, 255, 255));
        returnlogin.setText("Login");
        returnlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnlogin.setBorderPainted(false);
        returnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnloginActionPerformed(evt);
            }
        });
        jPanel1.add(returnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 60, -1));
        jPanel1.add(emailSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 30));

        usernameSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSignupActionPerformed(evt);
            }
        });
        jPanel1.add(usernameSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, 30));

        showPass1.setText("Show Password");
        showPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPass1ActionPerformed(evt);
            }
        });
        jPanel1.add(showPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        showPass2.setText("Show Password");
        showPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPass2ActionPerformed(evt);
            }
        });
        jPanel1.add(showPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));
        jPanel1.add(passwordSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 210, 30));
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupppp.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnloginActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnloginActionPerformed

    private void usernameSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameSignupActionPerformed

    private void createaccbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccbttnActionPerformed
        // TODO add your handling code here:
        String username = usernameSignup.getText().trim();
        String email = emailSignup.getText().trim();
        String password = passwordSignup.getText().trim();
        String confirmPassword = confirmpassword.getText().trim();
        String defaultUserType = "Staff";
       

        // Validate inputs
        if (username.isEmpty() || email.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Connect to the database
        Connection connection = DBKonek.getConnection();
        if (connection == null) {
            JOptionPane.showMessageDialog(null, "Database connection failed.");
            return;
        }


        // Prepare SQL statement to prevent SQL injection
        String sql = "INSERT INTO user (Username, Email, Password, User_type) VALUES (?, ?, ?, ?)";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, email);
            preparedStatement.setString(3, password); 
            preparedStatement.setString(4, defaultUserType);

            // Execute the update
            int rowsInserted = preparedStatement.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearField();
                
                showPass1.setSelected(false);
                showPass2.setSelected(false);

                // Mask the password fields again
                passwordSignup.setEchoChar('*');
                confirmpassword.setEchoChar('*');
            } else {
                JOptionPane.showMessageDialog(this, "Account creation failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error during account creation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_createaccbttnActionPerformed

    private void showPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPass2ActionPerformed
        if(showPass2.isSelected()){
        confirmpassword.setEchoChar((char)0);
        } else {
        confirmpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPass2ActionPerformed

    private void showPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPass1ActionPerformed
        if(showPass1.isSelected()){
        passwordSignup.setEchoChar((char)0);
        } else {
        passwordSignup.setEchoChar('*');
        }
    }//GEN-LAST:event_showPass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JButton createaccbttn;
    private javax.swing.JTextField emailSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordSignup;
    private javax.swing.JButton returnlogin;
    private javax.swing.JCheckBox showPass1;
    private javax.swing.JCheckBox showPass2;
    private javax.swing.JTextField usernameSignup;
    // End of variables declaration//GEN-END:variables
}
