

import database_connector.DBKonek;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    private Connection kon;
   
    public Login() {
        initComponents();
        DBKonek dbc = new DBKonek();
        kon = dbc.getConnection();
          usernametxtfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbttnActionPerformed(evt);
            }
        });

        passwordfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbttnActionPerformed(evt);
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernametxtfld = new javax.swing.JTextField();
        passwordfld = new javax.swing.JPasswordField();
        loginbttn = new javax.swing.JButton();
        clearbttn = new javax.swing.JButton();
        signupbttn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        showPass = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/vrms_icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jLabel1.setText("Videoke Rental Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 40));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        usernametxtfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtfldActionPerformed(evt);
            }
        });
        jPanel1.add(usernametxtfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 220, 30));

        passwordfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 220, 30));

        loginbttn.setBackground(new java.awt.Color(77, 77, 77));
        loginbttn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        loginbttn.setForeground(new java.awt.Color(255, 255, 255));
        loginbttn.setText("Login");
        loginbttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginbttn.setBorderPainted(false);
        loginbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbttnActionPerformed(evt);
            }
        });
        jPanel1.add(loginbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 120, 30));

        clearbttn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        clearbttn.setText("Clear");
        clearbttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearbttn.setBorderPainted(false);
        clearbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbttnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 80, 30));

        signupbttn.setBackground(new java.awt.Color(51, 51, 51));
        signupbttn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        signupbttn.setForeground(new java.awt.Color(255, 255, 255));
        signupbttn.setText("Sign Up");
        signupbttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signupbttn.setBorderPainted(false);
        signupbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbttnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 70, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel7.setText("Don't have account?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, 20));

        showPass.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel1.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guuuuuuuuuuuuuuuuuuui.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean isPassVisible = false;
    private String loggedInUser;

    private void usernametxtfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtfldActionPerformed

    private void passwordfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfldActionPerformed

    private void loginbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbttnActionPerformed
        // TODO add your handling code here:
    String username, password, userDB = null, passDB = null, usertypeDB = null;
    boolean found = false;

    try {
        DBKonek dbc = new DBKonek();
        kon = dbc.getConnection();

        // Check for empty input fields
        if (usernametxtfld.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (passwordfld.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get user inputs
        username = usernametxtfld.getText().trim();
        password = passwordfld.getText().trim();

        // Use PreparedStatement for safe querying
        String query = "SELECT * FROM user WHERE Username = ?";
        PreparedStatement ps = kon.prepareStatement(query);
        ps.setString(1, username);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            userDB = rs.getString("Username");
            passDB = rs.getString("Password");
            usertypeDB = rs.getString("User_type");
            found = true;
        }

        if (found) {
            if (password.equals(passDB)) {
                loggedInUser = userDB;

                if ("Staff".equalsIgnoreCase(usertypeDB)) {
                    new Staff().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Unknown user type", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect password", "Error!", JOptionPane.ERROR_MESSAGE);
                passwordfld.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect username or password", "Error!", JOptionPane.ERROR_MESSAGE);
            passwordfld.setText("");
        }

        // Close resources
        rs.close();
        ps.close();
        kon.close();

    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_loginbttnActionPerformed

    private void clearbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbttnActionPerformed
        // TODO add your handling code here:
        usernametxtfld.setText("");
        passwordfld.setText("");
        
        showPass.setSelected(false);
        passwordfld.setEchoChar('*');
    }//GEN-LAST:event_clearbttnActionPerformed

    private void signupbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbttnActionPerformed
        // TODO add your handling code here:
        Signup signup = new Signup();
        signup.setVisible(true);
        dispose();
    }//GEN-LAST:event_signupbttnActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        if (showPass.isSelected()){
        passwordfld.setEchoChar((char)0);
        }
        else {
        passwordfld.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbttn;
    private javax.swing.JPasswordField passwordfld;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JButton signupbttn;
    private javax.swing.JTextField usernametxtfld;
    // End of variables declaration//GEN-END:variables
}