/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import database_connector.DBKonek;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Staff extends javax.swing.JFrame {

    /**
     *
     */
    public Staff() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        customermngmnt = new javax.swing.JButton();
        usagemonitor = new javax.swing.JButton();
        equipmngmnt = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        logoutstaff = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        machine1bttn = new javax.swing.JButton();
        machine2bttn = new javax.swing.JButton();
        machine3bttn = new javax.swing.JButton();
        machine4bttn = new javax.swing.JButton();
        machine5bttn = new javax.swing.JButton();
        machine6bttn = new javax.swing.JButton();
        info = new java.awt.TextArea();
        rentbttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        bookingmngmnt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconAdmin.png"))); // NOI18N
        jLabel2.setText("STAFF");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        dashboard.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dashicon.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 40));

        customermngmnt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        customermngmnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/customermngmnt.png"))); // NOI18N
        customermngmnt.setText("Customer Management");
        customermngmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customermngmntActionPerformed(evt);
            }
        });
        jPanel1.add(customermngmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 40));

        usagemonitor.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        usagemonitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usagemonitor.png"))); // NOI18N
        usagemonitor.setText("Usage Monitoring");
        usagemonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usagemonitorActionPerformed(evt);
            }
        });
        jPanel1.add(usagemonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 40));

        equipmngmnt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        equipmngmnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/equipmngmnt.png"))); // NOI18N
        equipmngmnt.setText("Equipment Management");
        equipmngmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmngmntActionPerformed(evt);
            }
        });
        jPanel1.add(equipmngmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 210, 40));

        reports.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reportssss.png"))); // NOI18N
        reports.setText("Reports");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        jPanel1.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, 40));

        logoutstaff.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        logoutstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logouticon.png"))); // NOI18N
        logoutstaff.setText("Log out");
        logoutstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutstaffActionPerformed(evt);
            }
        });
        jPanel1.add(logoutstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 120, 30));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(740, 490));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setVerifyInputWhenFocusTarget(false);

        machine1bttn.setBackground(new java.awt.Color(102, 204, 255));
        machine1bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/machine1.png"))); // NOI18N
        machine1bttn.setBorder(new javax.swing.border.MatteBorder(null));
        machine1bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine1bttnActionPerformed(evt);
            }
        });

        machine2bttn.setBackground(new java.awt.Color(102, 204, 255));
        machine2bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/machine2.png"))); // NOI18N
        machine2bttn.setBorder(new javax.swing.border.MatteBorder(null));
        machine2bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine2bttnActionPerformed(evt);
            }
        });

        machine3bttn.setBackground(new java.awt.Color(102, 204, 255));
        machine3bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/machine3.png"))); // NOI18N
        machine3bttn.setBorder(new javax.swing.border.MatteBorder(null));
        machine3bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine3bttnActionPerformed(evt);
            }
        });

        machine4bttn.setBackground(new java.awt.Color(102, 204, 255));
        machine4bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/machine4.png"))); // NOI18N
        machine4bttn.setBorder(new javax.swing.border.MatteBorder(null));
        machine4bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine4bttnActionPerformed(evt);
            }
        });

        machine5bttn.setBackground(new java.awt.Color(102, 204, 255));
        machine5bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/machinee5.png"))); // NOI18N
        machine5bttn.setBorder(new javax.swing.border.MatteBorder(null));
        machine5bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine5bttnActionPerformed(evt);
            }
        });

        machine6bttn.setBackground(new java.awt.Color(102, 204, 255));
        machine6bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/machine6.png"))); // NOI18N
        machine6bttn.setBorder(new javax.swing.border.MatteBorder(null));
        machine6bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine6bttnActionPerformed(evt);
            }
        });

        rentbttn.setBackground(new java.awt.Color(0, 204, 0));
        rentbttn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        rentbttn.setText("RENT");
        rentbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentbttnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel3.setText("Machine 1");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel4.setText("Machine 2");

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel5.setText("Machine 6");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel6.setText("Machine 3");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel7.setText("Machine 4");

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel8.setText("Machine 5");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(machine5bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(machine6bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(rentbttn))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel5))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(machine1bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machine3bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(machine2bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machine4bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))))
                        .addGap(44, 44, 44)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(machine1bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addGap(3, 3, 3)
                                .addComponent(machine3bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(machine2bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(3, 3, 3)
                                .addComponent(machine4bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7)))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(machine5bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(machine6bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(rentbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking Management", jPanel9);

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dashboard", jPanel10);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Customer Management", jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Usage Monitoring", jPanel12);

        jPanel13.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Equipment  Management", jPanel13);

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reports", jPanel14);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 740, 530));

        bookingmngmnt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        bookingmngmnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bookingggicon.png"))); // NOI18N
        bookingmngmnt.setText("Booking Management");
        bookingmngmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingmngmntActionPerformed(evt);
            }
        });
        jPanel1.add(bookingmngmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guiadmindashh.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_dashboardActionPerformed

    private void customermngmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customermngmntActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_customermngmntActionPerformed

    private void equipmngmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmngmntActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_equipmngmntActionPerformed

    private void usagemonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usagemonitorActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_usagemonitorActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_reportsActionPerformed

    private void logoutstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutstaffActionPerformed
        // TODO add your handling code here:
        Login loginFrame = new Login();  
        loginFrame.setVisible(true);    
        this.dispose();
    }//GEN-LAST:event_logoutstaffActionPerformed

    private void bookingmngmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingmngmntActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_bookingmngmntActionPerformed

    private void machine1bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine1bttnActionPerformed
        // TODO add your handling code here:
          // Connect to the database
    Connection connection = DBKonek.getConnection();

    if (connection == null) {
        JOptionPane.showMessageDialog(null, "Database connection failed.");
        return;
    }

    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        String sql = "SELECT machine_name, status, remarks, price FROM videoke_machines WHERE machine_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 1); // Fetch data for machine_id = 1

        rs = pstmt.executeQuery();

        if (rs.next()) {
            String machineName = rs.getString("machine_name");
            String status = rs.getString("status");
            String remarks = rs.getString("remarks");
            double price = rs.getDouble("price");

            String machineInfo = "Machine Name: " + machineName +
                                 "\nStatus: " + status +
                                 "\nRemarks: " + remarks +
                                 "\nPrice: ₱" + String.format("%.2f", price);

            // Set the info to the JTextArea named 'info'
            info.setText(machineInfo);
        } else {
            info.setText("No data found for Machine ID 1.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        info.setText("Error retrieving machine data.");
    } 

    }//GEN-LAST:event_machine1bttnActionPerformed

    private void machine2bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine2bttnActionPerformed
        // TODO add your handling code here:
    Connection connection = DBKonek.getConnection();

    if (connection == null) {
        JOptionPane.showMessageDialog(null, "Database connection failed.");
        return;
    }

    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        String sql = "SELECT machine_name, status, remarks, price FROM videoke_machines WHERE machine_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 2); // Fetch data for machine_id = 1

        rs = pstmt.executeQuery();

        if (rs.next()) {
            String machineName = rs.getString("machine_name");
            String status = rs.getString("status");
            String remarks = rs.getString("remarks");
            double price = rs.getDouble("price");

            String machineInfo = "Machine Name: " + machineName +
                                 "\nStatus: " + status +
                                 "\nRemarks: " + remarks +
                                 "\nPrice: ₱" + String.format("%.2f", price);

            // Set the info to the JTextArea named 'info'
            info.setText(machineInfo);
        } else {
            info.setText("No data found for Machine ID 2.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        info.setText("Error retrieving machine data.");
    }
    }//GEN-LAST:event_machine2bttnActionPerformed

    private void machine3bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine3bttnActionPerformed
        // TODO add your handling code here:
       Connection connection = DBKonek.getConnection();

    if (connection == null) {
        JOptionPane.showMessageDialog(null, "Database connection failed.");
        return;
    }

    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        String sql = "SELECT machine_name, status, remarks, price FROM videoke_machines WHERE machine_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 3); // Fetch data for machine_id = 1

        rs = pstmt.executeQuery();

        if (rs.next()) {
            String machineName = rs.getString("machine_name");
            String status = rs.getString("status");
            String remarks = rs.getString("remarks");
            double price = rs.getDouble("price");

            String machineInfo = "Machine Name: " + machineName +
                                 "\nStatus: " + status +
                                 "\nRemarks: " + remarks +
                                 "\nPrice: ₱" + String.format("%.2f", price);

            // Set the info to the JTextArea named 'info'
            info.setText(machineInfo);
        } else {
            info.setText("No data found for Machine ID 2.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        info.setText("Error retrieving machine data.");
    }
        
        
    }//GEN-LAST:event_machine3bttnActionPerformed

    private void machine4bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine4bttnActionPerformed
        // TODO add your handling code here:
        Connection connection = DBKonek.getConnection();

    if (connection == null) {
        JOptionPane.showMessageDialog(null, "Database connection failed.");
        return;
    }

    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        String sql = "SELECT machine_name, status, remarks, price FROM videoke_machines WHERE machine_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 4); // Fetch data for machine_id = 1

        rs = pstmt.executeQuery();

        if (rs.next()) {
            String machineName = rs.getString("machine_name");
            String status = rs.getString("status");
            String remarks = rs.getString("remarks");
            double price = rs.getDouble("price");

            String machineInfo = "Machine Name: " + machineName +
                                 "\nStatus: " + status +
                                 "\nRemarks: " + remarks +
                                 "\nPrice: ₱" + String.format("%.2f", price);

            // Set the info to the JTextArea named 'info'
            info.setText(machineInfo);
        } else {
            info.setText("No data found for Machine ID 2.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        info.setText("Error retrieving machine data.");
    }
    }//GEN-LAST:event_machine4bttnActionPerformed

    private void machine5bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine5bttnActionPerformed
        // TODO add your handling code here:
        Connection connection = DBKonek.getConnection();

    if (connection == null) {
        JOptionPane.showMessageDialog(null, "Database connection failed.");
        return;
    }

    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        String sql = "SELECT machine_name, status, remarks, price FROM videoke_machines WHERE machine_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 5); // Fetch data for machine_id = 1

        rs = pstmt.executeQuery();

        if (rs.next()) {
            String machineName = rs.getString("machine_name");
            String status = rs.getString("status");
            String remarks = rs.getString("remarks");
            double price = rs.getDouble("price");

            String machineInfo = "Machine Name: " + machineName +
                                 "\nStatus: " + status +
                                 "\nRemarks: " + remarks +
                                 "\nPrice: ₱" + String.format("%.2f", price);

            // Set the info to the JTextArea named 'info'
            info.setText(machineInfo);
        } else {
            info.setText("No data found for Machine ID 2.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        info.setText("Error retrieving machine data.");
    }
    }//GEN-LAST:event_machine5bttnActionPerformed

    private void machine6bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine6bttnActionPerformed
        // TODO add your handling code here:
        Connection connection = DBKonek.getConnection();

    if (connection == null) {
        JOptionPane.showMessageDialog(null, "Database connection failed.");
        return;
    }

    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        String sql = "SELECT machine_name, status, remarks, price FROM videoke_machines WHERE machine_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 6); // Fetch data for machine_id = 1

        rs = pstmt.executeQuery();

        if (rs.next()) {
            String machineName = rs.getString("machine_name");
            String status = rs.getString("status");
            String remarks = rs.getString("remarks");
            double price = rs.getDouble("price");

            String machineInfo = "Machine Name: " + machineName +
                                 "\nStatus: " + status +
                                 "\nRemarks: " + remarks +
                                 "\nPrice: ₱" + String.format("%.2f", price);

            // Set the info to the JTextArea named 'info'
            info.setText(machineInfo);
        } else {
            info.setText("No data found for Machine ID 2.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        info.setText("Error retrieving machine data.");
    }
    }//GEN-LAST:event_machine6bttnActionPerformed

    private void rentbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentbttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentbttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingmngmnt;
    private javax.swing.JButton customermngmnt;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton equipmngmnt;
    private java.awt.TextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutstaff;
    private javax.swing.JButton machine1bttn;
    private javax.swing.JButton machine2bttn;
    private javax.swing.JButton machine3bttn;
    private javax.swing.JButton machine4bttn;
    private javax.swing.JButton machine5bttn;
    private javax.swing.JButton machine6bttn;
    private javax.swing.JButton rentbttn;
    private javax.swing.JButton reports;
    private javax.swing.JButton usagemonitor;
    // End of variables declaration//GEN-END:variables
}
